name: CI-BlackDuck-SCA-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: [ubuntu-latest]
    environment: TEST
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Black Duck SCA Scan
      id: black-duck-sca-scan
      uses: blackduck-inc/black-duck-security-scan@v2
      
      ### Configure DETECT environment variables
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
      with:
        ### SCANNING: Required fields
        blackducksca_url: ${{ vars.BLACKDUCK_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
        # blackducksca_fixpr_enabled: true
        # blackducksca_prComment_enabled: true
        # blackducksca_reports_sarif_create: true
        # blackducksca_upload_sarif_report: true
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        # include_diagnostics: false